### ISSUE TITLE
Global Placement in rails 4 app

### ISSUE THREAD

**Issue by sandovalg** [corthmann/bigcommerce-oauth-api#43]
Where is the best place to access this globally in a rails 4 application. For legacy as either a class or as a Module. Have not found any wiki articles.

**Comment by corthmann** [comment]
I haven't used the wiki section up until now but have written documentation in the `README.md` file. I might create a few wiki pages when I have time, but for now I hope the following answers your question.

To install this gem in your rails application you need to add this line to your `Gemfile`:

gem 'bigcommerce-oauth-api'

You can then configure the gem globally by creating the following initializer in your rails application (`config/initializers/bigcommerce-oauth-api.rb`):

```
require 'bigcommerce-oauth-api'

# module legacy (basic auth) configuration
BigcommerceOAuthAPI.configure do |config|
  config.endpoint = 'YOU STORE URL (https://store-XYZ.mybigcommerce.com)'
  config.user_name = 'API USER NAME'
  config.api_key = 'API KEY'
end
```

You will then be able to use the library in your controllers like this:

```
# initialize the client using the global configuration
client = BigcommerceOAuthAPI::Client.new
# send api request to BigCommerce
products = client.products(limit: 250)
```

You can also override the globally defined configuration in your controller by initializing the client with a different configuration:

```
# initialize the client overrwriting the configuration in config/initializers/bigcommerce-oauth-api.rb
client = BigcommerceOAuthAPI::Client.new(
                                endpoint: 'ANOTHER STORE URL (ex. https://store-XYZ.mybigcommerce.com)',
                                user_name: 'ANOTHER API USER NAME',
                                api_key: 'ANOTHER API KEY'
)
# send api request to BigCommerce
products = client.products(limit: 250) # send api request to BigCommerce
```
