### ISSUE TITLE
oidc

### ISSUE THREAD

**Issue by walshe** [corthmann/bigcommerce-oauth-api#47]
hi, do you know if bigcommerce supports oidc ?

**Comment by corthmann** [comment]
Hi @walshe . As far as I know Bigcommerce does not support oidc.

If you're interested in Single Sign-On (SSO) with Bigcommerce, then you can achieve it through their customer login api: https://developer.bigcommerce.com/api/v2/#customer-login-api

The customer login api isn't added to this gem yet, but I can easily and quickly add it if you need it.
